### ISSUE TITLE
Workaround needed for PortentaH7 design flaws

### ISSUE THREAD

**Issue by DavidArmstrong** [DavidArmstrong/SCL3300#13]
Apparently the Arduino port for the "PortentaH7", a platform I've never even heard of, uses some non-standard design decisions when defining global macros.  The side effect of this is that is mucks with any other code that just happens to have variables defined with the exact same string pattern.

For example, the library uses a variable called CRC, which is straight from the Murata datasheet for doing CRC calculations.  This PortentaH7 port has a macro that ends up replacing every occurrence of that string with its own coding.  So now every internal variable may need to be changed to avoid this type of issue coming up in the future.

**Comment by JLH-94** [comment]
Hello, 
thanks for your help and explanation.
I also posted the problem in the PortentaH7-Forum and got an first fast fix/hack i will try. 

So the real Problem is the mbed-lib. of the PortentaH7 board, i will hope for an update/rework of this flaw from arduino in the future.

Just for the completeness:
[https://forum.arduino.cc/index.php?topic=698825.0](url)
